phantomx_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 0.50, i: 0.01, d: 0.25}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 0.50, i: 0.01, d: 0.25}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 0.50, i: 0.01, d: 0.25}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 0.50, i: 0.01, d: 0.25}

Maulesh/phantomx_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 0.50, i: 0.01, d: 0.25}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 0.50, i: 0.01, d: 0.25}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 0.50, i: 0.01, d: 0.25}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 0.50, i: 0.01, d: 0.25}
